language: objective-c
xcode_project: InAppPurchase.xcodeproj
xcode_scheme: InAppPurchaseTests
osx_image: xcode12.2
xcode_sdk: iphonesimulator

before_install:
  - brew update && brew bundle
  - SIMULATOR_UUID_14=`xcrun simctl create "iPhone Xs" com.apple.CoreSimulator.SimDeviceType.iPhone-XS com.apple.CoreSimulator.SimRuntime.iOS-14-2`
script:
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -scheme InAppPurchaseTests -configuration Debug -sdk iphonesimulator -destination "id=$SIMULATOR_UUID_14" ENABLE_TESTABILITY=YES | xcpretty
after_success:
    - bash <(curl -s https://codecov.io/bash)
