name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Coverage file
      uses: sersoft-gmbh/swift-coverage-action@v2
      with:
        format: lcov
    - name: Codecov
      uses: codecov/codecov-action@v2.0.2
      with:
        files: ./.swiftcov/InAppPurchasePackageTests.xctest.coverage.lcov

